### ISSUE TITLE
A question about theorem 3.1

### ISSUE THREAD

**Issue by myu1999** [Mingxiao-Li/TS-DPM#1]
Hello author, your work is very interesting, and I am very glad to read this. However, I think there is a certain problem with the proof of theorem 3.1 in the original text. According to your evidence in Appendix J.1, substituting Equation 20 into Equation 13 does not give us the standard Equation 21. Can you give me some help or guidance? How did Equations 20 to 21 come from in the appendix? Thank you so much!

**Comment by Mingxiao-Li** [comment]
> Hello author, your work is very interesting, and I am very glad to read this. However, I think there is a certain problem with the proof of theorem 3.1 in the original text. According to your evidence in Appendix J.1, substituting Equation 20 into Equation 13 does not give us the standard Equation 21. Can you give me some help or guidance? How did Equations 20 to 21 come from in the appendix? Thank you so much!

Hi, thanks for your interests and raising this question. We carefully rechecked our derivation in the appendix and the scratch papers. We found that we made a mistake in the derivation in the appendix which is different from that in our scratch paper, but the results are the same and correct. The mistake is in equation 9, from the second line to the third line. The second term shoule be $\frac{1}{1-\bar{\alpha}_{t_s}}Tr(\Sigma)$ (the d in the numerator in the current version shoule be removed). The equation 13 will then become $\Sigma ts = \frac{1}{d}Tr(\Sigma t-1)+\frac{1}{d}||e||^2$.  You can obtain equation 21 by simply plug equation 20 to the new euqation 13. We will also update our arxiv version. You can check the new version next week. Kindly let me know if you have any further questions.

**Comment by myu1999** [comment]
感谢您的回复，我确实还有几个小问题，我感觉您也是中国人，索性就用中文提问，由于公式有点多，我以附件的形式给出，打扰您了！ 
[Questions-TS-DPM.pdf](https://github.com/user-attachments/files/15848197/Questions-TS-DPM.pdf)

**Comment by Mingxiao-Li** [comment]
> 感谢您的回复，我确实还有几个小问题，我感觉您也是中国人，索性就用中文提问，由于公式有点多，我以附件的形式给出，打扰您了！ [Questions-TS-DPM.pdf](https://github.com/user-attachments/files/15848197/Questions-TS-DPM.pdf)

不好意思，我们的notation可能有点乱.
关于pdf里的问题1，公式20里的左边 $\sigma_(t-1)$ 是单样本的内部方差， 右边$\sigma$是真实方差，即公式13右边的   $\Sigma_(t-1)$, 你pdf里面带反了，这样带进去就能得到最后的公式了。 
pdf里的第二个问题，我们的notation确实有点乱，在公式9当中的$\Sigma_(ts)$是个矩阵对角线元素为$1-\alpha_(ts)$,所以1/2 log那边需要一个d,  公式13中  $\Sigma_(ts)$ 应该换为 $\sigma_(ts)$ 此时我们想表示的是个表量.
关于第三个问题,这是个很好的问题,  analytic dpm通过最小化前向反向的kl距离推出了解析最优方差，在我们推导中t-1的方差需要的是每次sample中每个样本分布的真实方差， 因为预测误差的存在这两个数值应该是不一样的。确实， 步骤多了指标下降，exposure bia很有可能是一个原因，但是更严格的验证还是需要相应实验来论证一下。
